### ISSUE TITLE
Unsupported format in Rules?

### ISSUE THREAD

**Issue by jreynders** [mindedsecurity/semgrep-rules-android-security#13]
I get these types of errors when running on Kali Linux:

semgrep error: invalid language: xml
  --> rules/code/mstg-code-2.yaml:5
4 |     languages:
5 |       - xml
6 |     metadata:
7 |       authors:

unsupported language: xml. supported languages are: bash, c, c#, c++, cpp, csharp, dart, docker, dockerfile, elixir, ex, generic, go, golang, hack, hcl, html, java, javascript, js, json, jsonnet, julia, kotlin, kt, lua, none, ocaml, php, py, python, python2, python3, r, regex, ruby, rust, scala, sh, sol, solidity, swift, terraform, tf, ts, typescript, vue, yaml

**Comment by gand3lf** [comment]
Hi @jreynders,
can you let me know the version of Semgrep you have installed?
I'm trying with the version 1.45.0 and it works. In any case, you can update Semgrep with this command:
`python3 -m pip install --upgrade semgrep`

**Comment by jreynders** [comment]
That did it, my initial install must not have upgraded Semgrep.  It is working now on 1.4.5.
Thanks
