### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by gawi151** [mindedsecurity/semgrep-rules-android-security#14]
Hi, I have a general question about Kotlin support - Are there any plans to make it work for Kotlin too? All current rules are Java only.

**Comment by gand3lf** [comment]
Hi @gawi151,
as outlined in the readme, these guidelines are formulated with the viewpoint of a penetration tester. Typically, in such situations, the target of your activities is an APK file that can be extracted and decompiled. If you decompile an Android application written in Kotlin, you can acquire the Java source code. Consequently, for now, we are not planning to extend the implementation of these rules to Kotlin.
