### ISSUE TITLE
[Enhancement] Minimizing false negatives in WebView rules while potentially increasing false positives

### ISSUE THREAD

**Issue by federicodotta** [mindedsecurity/semgrep-rules-android-security#2]
Hi,

First of all, thank you for the great project! Very helpful!

I tested the rules on an Android application and noticed that it didn't flag certain issues related to WebView that I was getting using some rules I had written earlier.

I looked at the rules responsible for these checks (as an example [platform/mstg-platform-5.yaml](https://github.com/mindedsecurity/semgrep-rules-android-security/blob/main/rules/platform/mstg-platform-5.yaml)) and I think that the reason they did not find the issue in my application was that the rules are very specific. This way, the rules minimize greatly false positives but can be more prone to false negatives. In a CI/CD pipeline false positives can be a problem but during pentest personally I prefer to have more false positives than false negatives. 

As an example, if I'm not wrong the platform/mstg-platform-5.yaml rule cannot detect vulnerable code if the WebView is not defined in the same location when the "setJavaScriptEnabled" method is called, or when the WebView settings are first stored in a variable and then the "setJavaScriptEnabled" method is called, like in the following code:

```java
WebSettings webViewSettings = webview.getSettings();
webViewSettings.setJavaScriptEnabled(true);
```

What do you think to change the rules to be less specific? An example can be the following one:

```yaml
  pattern-either:  
      - pattern: $OBJ.setJavaScriptEnabled(true)
      - pattern: setJavaScriptEnabled(true)
```

This rules may have some false positives but will be less prone to false negatives.

The same applies also for the other rules that check WebView issues (and potentially also other kind of vulnerabilities).

Some months ago I wrote some rules with this approach to check for WebView issues following the OWASP Mobile Testing Guide. You can find the rules [here](https://github.com/federicodotta/semgrep-rules/blob/main/java/android-webview/android-webview-java-apps3c.yaml).

I opened a issue instead of sending a pull request because maybe you prefer an approach that minimize false positives.

Thanks again for sharing this great work!

**Comment by gand3lf** [comment]
Hi Federico, thanks for the suggestion.
I agree with your analysis, please proceed with the pull request!

Glad you liked the project :smiley:

**Comment by gand3lf** [comment]
Done, next time feel free to open a pull request. Thanks
